import os

def format_readme(name, description, installation, usage):
    """Formats project details into a Markdown string."""
    return f"""# {name}

## Description
{description}

## Installation
```bash
{installation}
```

## Usage
```python
{usage}
```

---
*Generated by README Generator*
"""

def get_input(prompt_text):
    """Helper to get user input."""
    return input(f"{prompt_text}: ").strip()

def main():
    print("--- README Generator ---")

    name = get_input("Project Name")
    description = get_input("Project Description")
    installation = get_input("Installation Steps")
    usage = get_input("Usage Examples")

    # Simple validation
    if not name:
        name = "My Project"

    content = format_readme(name, description, installation, usage)

    # Save to README.md in the current directory (task1)
    file_path = os.path.join(os.path.dirname(__file__), "README.md")

    with open(file_path, "w") as f:
        f.write(content)

    print(f"\n✅ README.md has been generated at: {file_path}")

if __name__ == "__main__":
    main()
